#ifndef MAIN_H
#define MAIN_H

//PROGRAMME: robotique
//DESCRIPTION: programme qui sert de base pour l'introduction a la programmation du CRC Atmega 2560 dans l'environnement CrcLib

//HISTORIQUE:
// 2025-11-19, Yves Roy: création

//inclusions globales
//pas d'inclusions globales

//INFORMATION PUBLIQUE:
//Definitions publiques:
//pas de definitions publiques

//DEFINITIONS REQUISES PAR LE MODULE:
//Dependances materielles:
#define PILOTEENTREESW1_BROCHE                                      CRC_DIG_1
#define PILOTEENTREESWF_BROCHE                                      CRC_DIG_2
#define PILOTEENTREESWO_BROCHE                                      CRC_DIG_3
#define PILOTEENTREESWB_BROCHE                                      CRC_DIG_4
#define PILOTEENTREESWH_BROCHE                                      CRC_DIG_5
#define PILOTEENTREESWS_BROCHE                                      CRC_DIG_6
#define PILOTEENTREESWV_BROCHE                                      CRC_DIG_7
#define PILOTEENTREESWI_BROCHE                                      CRC_DIG_8
#define PILOTESORTIEDEL_BROCHE                                      CRC_DIG_9
#define PILOTESORTIET1_BROCHE                                       CRC_DIG_10

#define INTERFACEVEXPINCE_BROCHE                                    CRC_PWM_1
#define INTERFACEVEXBRAS_BROCHE                                     CRC_PWM_2
#define INTERFACEVEXELEVATEUR_BROCHE                                CRC_PWM_3
#define INTERFACEVEXGAUCHE_BROCHE                                   CRC_PWM_4
#define INTERFACEVEXDROIT_BROCHE                                    CRC_PWM_5

#define PILOTEENTREESW1_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWF_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWO_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWB_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWH_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWS_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWV_MODE_FLOTTANT_AVEC_PULL_UP
#define PILOTEENTREESWI_MODE_FLOTTANT_AVEC_PULL_UP

#define PILOTESORTIEDEL_ETAT_INITIAL_A_ZERO
#define PILOTESORTIET1_ETAT_INITIAL_A_ZERO

#define INTERFACEENTREESW1_VALEUR_LUE_SI_ACTIVE                     0
#define INTERFACEENTREESW1_VALEUR_LUE_SI_INACTIVE                   1
#define INTERFACEENTREESW1_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESW1_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWF_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWF_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWF_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWF_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWO_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWO_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWO_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWO_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWB_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWB_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWB_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWB_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWH_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWH_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWH_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWH_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWS_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWS_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWS_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWS_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWV_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWV_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWV_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWV_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACEENTREESWI_VALEUR_LUE_SI_ACTIVE                     1   
#define INTERFACEENTREESWI_VALEUR_LUE_SI_INACTIVE                   0
#define INTERFACEENTREESWI_FREQUENCE_DES_LECTURES_EN_HZ             250
#define INTERFACEENTREESWI_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION  10

#define INTERFACESORTIEDEL_VALEUR_POUR_ALLUMER                      1
#define INTERFACESORTIEDEL_VALEUR_POUR_ETEINDRE                     0

#define INTERFACESORTIET1_VALEUR_POUR_ALLUMER                       1
#define INTERFACESORTIET1_VALEUR_POUR_ETEINDRE                      0

#define INTERFACEVEXPINCE_DUREE_MINIMALE_EN_US                      1000
#define INTERFACEVEXPINCE_DUREE_MAXIMALE_EN_US                      2000
#define INTERFACEVEXPINCE_VALEUR_INITIALE                           0
#define INTERFACEVEXPINCE_INVERSION_DE_COMMANDE_PAS_REQUISE

#define INTERFACEVEXBRAS_DUREE_MINIMALE_EN_US                       1000
#define INTERFACEVEXBRAS_DUREE_MAXIMALE_EN_US                       2000
#define INTERFACEVEXBRAS_VALEUR_INITIALE                            0
#define INTERFACEVEXBRAS_INVERSION_DE_COMMANDE_PAS_REQUISE

#define INTERFACEVEXELEVATEUR_DUREE_MINIMALE_EN_US                  1000
#define INTERFACEVEXELEVATEUR_DUREE_MAXIMALE_EN_US                  2000
#define INTERFACEVEXELEVATEUR_VALEUR_INITIALE                       0
#define INTERFACEVEXELEVATEUR_INVERSION_DE_COMMANDE_PAS_REQUISE

#define INTERFACEVEXGAUCHE_DUREE_MINIMALE_EN_US                     1000
#define INTERFACEVEXGAUCHE_DUREE_MAXIMALE_EN_US                     2000
#define INTERFACEVEXGAUCHE_VALEUR_INITIALE                          0
#define INTERFACEVEXGAUCHE_INVERSION_DE_COMMANDE_PAS_REQUISE

#define INTERFACEVEXDROIT_DUREE_MINIMALE_EN_US                      1000
#define INTERFACEVEXDROIT_DUREE_MAXIMALE_EN_US                      2000
#define INTERFACEVEXDROIT_VALEUR_INITIALE                           0
#define INTERFACEVEXDROIT_INVERSION_DE_COMMANDE_REQUISE

#define PROCESSUSTEMOIN_BOUTON_TEMOIN                               SERVICEMANETTE_BOUTON_LOGO
#define PROCESSUSPINCE_BOUTON_FERMER                                SERVICEMANETTE_BOUTON_BACK
#define PROCESSUSPINCE_BOUTON_OUVRIR                                SERVICEMANETTE_BOUTON_START
#define PROCESSUSBRAS_BOUTON_POSITION_SUPERIEURE                    SERVICEMANETTE_BOUTON_Y
#define PROCESSUSBRAS_BOUTON_POSITION_VERTICALE                     SERVICEMANETTE_BOUTON_X
#define PROCESSUSBRAS_BOUTON_POSITION_INFERIEURE                    SERVICEMANETTE_BOUTON_A
#define PROCESSUSBRAS_BOUTON_POSITION_INVERSEE                      SERVICEMANETTE_BOUTON_B
#define PROCESSUSELEVATEUR_BOUTON_DESCENDRE                         SERVICEMANETTE_BOUTON_GAUCHE
#define PROCESSUSELEVATEUR_BOUTON_MONTER                            SERVICEMANETTE_BOUTON_DROIT
#define PROCESSUSMOTORISATION_BOUTON_JOYSTICK                       SERVICEMANETTE_BOUTON_JOYSTICK_GAUCHE

#define PROCESSUSMOTORISATION_JOYSTICK_X                            SERVICEMANETTE_JOYSTICK_GAUCHE_X
#define PROCESSUSMOTORISATION_JOYSTICK_Y                            SERVICEMANETTE_JOYSTICK_GAUCHE_Y

#define PROCESSUSPINCE_VALEUR_POUR_FERMER                           127
#define PROCESSUSPINCE_VALEUR_POUR_OUVRIR                           -128
#define PROCESSUSPINCE_VALEUR_POUR_ENTROUVRIR                       -50
#define PROCESSUSPINCE_TEMPS_MAXIMUM_POUR_FERMER_EN_SECONDES        3
#define PROCESSUSPINCE_TEMPS_MAXIMUM_POUR_OUVRIR_EN_SECONDES        3
#define PROCESSUSPINCE_TEMPS_POUR_ENTROUVRIR_EN_MS                  500

#define PROCESSUSBRAS_VALEUR_POUR_INFERIEURE_VERS_SUPERIEURE        127
#define PROCESSUSBRAS_VALEUR_POUR_INFERIEURE_VERS_VERTICALE         127
#define PROCESSUSBRAS_VALEUR_POUR_SUPERIEURE_VERS_VERTICALE         127
#define PROCESSUSBRAS_VALEUR_POUR_SUPERIEURE_VERS_INFERIEURE        -128
#define PROCESSUSBRAS_VALEUR_POUR_VERTICALE_VERS_SUPERIEURE         -128
#define PROCESSUSBRAS_VALEUR_POUR_VERTICALE_VERS_INFERIEURE         -128
#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_INFERIEURE_VERS_SUPERIEURE_EN_SECONDES 6
#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_INFERIEURE_VERS_VERTICALE_EN_SECONDES  9
#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_SUPERIEURE_VERS_VERTICALE_EN_SECONDES  3
#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_SUPERIEURE_VERS_INFERIEURE_EN_SECONDES 6
#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_VERTICALE_VERS_SUPERIEURE_EN_SECONDES  3
#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_VERTICALE_VERS_INFERIEURE_EN_SECONDES  9

#define PROCESSUSELEVATEUR_VALEUR_POUR_DESCENDRE                    127
#define PROCESSUSELEVATEUR_VALEUR_POUR_MONTER                       -127
#define PROCESSUSELEVATEUR_VALEUR_POUR_REMONTER                     -25
#define PROCESSUSELEVATEUR_TEMPS_MAXIMUM_POUR_DESCENDRE_EN_SECONDES 3
#define PROCESSUSELEVATEUR_TEMPS_MAXIMUM_POUR_MONTER_EN_SECONDES    3
#define PROCESSUSELEVATEUR_TEMPS_POUR_REMONTER_EN_MS                500

#define PROCESSUSMOTORISATION_VALEUR_MAXIMALE                       125
#define PROCESSUSMOTORISATION_SEUIL_DE_DETECTION                    5
#define PROCESSUSMOTORISATION_VALEUR_REDUITE_MAXIMALE               50

//Dependances logicielles:
#define SERVICETASKSERVER_PERIODE_EN_US                             (4000L)
#define SERVICEBASEDETEMPS_FREQUENCE_EN_HZ                          ((1000000L)/SERVICETASKSERVER_PERIODE_EN_US)
#define PROCESSUSCLIGNOTANT_TEMPS_ALLUME_EN_MS                      500
#define PROCESSUSCLIGNOTANT_TEMPS_ETEINT_EN_MS                      500
#define PROCESSUSPINCE_TEMPS_DE_DEPART_EN_SECONDES                  2
#define PROCESSUSBRAS_TEMPS_DE_DEPART_EN_SECONDES                   2
#define PROCESSUSELEVATEUR_TEMPS_DE_DEPART_EN_SECONDES              2

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES                         15
#define INTERFACEENTREESW1_PHASE                                    0
#define INTERFACEENTREESWF_PHASE                                    1
#define INTERFACEENTREESWO_PHASE                                    2
#define INTERFACEENTREESWB_PHASE                                    3
#define INTERFACEENTREESWH_PHASE                                    4
#define INTERFACEENTREESWS_PHASE                                    5
#define INTERFACEENTREESWV_PHASE                                    6
#define INTERFACEENTREESWI_PHASE                                    7
#define SERVICEMANETTE_PHASE                                        8
#define PROCESSUSCLIGNOTANT_PHASE                                   9
#define PROCESSUSTEMOIN_PHASE                                       10
#define PROCESSUSPINCE_PHASE                                        11
#define PROCESSUSBRAS_PHASE                                         12
#define PROCESSUSELEVATEUR_PHASE                                    13
#define PROCESSUSMOTORISATION_PHASE                                 14

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES_DANS_LOOP               1
#define INTERFACECRCCONNECT_PHASE_DANS_LOOP                         0

//INFORMATION PUBLIQUE:
//Definitions publiques:
//pas de definitions publiques

//Variables publiques:
//pas de variables publiques

//Fonctions publiques:
//pas de fonctions publiques

#endif
