#ifndef PROCESSUSBRAS_H
#define PROCESSUSBRAS_H

//MODULE: processusBras
//DESCRIPTION: implemente la gestion d'un moteur commande par un variateur VEXPRO. Deux boutons
//du CRCConnect sont utilises pour selectionner le sens de rotation du moteur. Les vitesses
//de rotation sont determinees par les definitions
//PROCESSUS

//HISTORIQUE:
// 2025-12-02, Yves Roy, creation

//DEFINITIONS REQUISES PAR LE MODULE:
//Dependances materielles
//(copiez et adaptez ce qui suit dans "main.h")
//#define PROCESSUSBRAS_BOUTON_POSITION_SUPERIEURE  SERVICEMANETTE_BOUTON_Y
//#define PROCESSUSBRAS_BOUTON_POSITION_VERTICALE SERVICEMANETTE_BOUTON_X
//#define PROCESSUSBRAS_BOUTON_POSITION_INFERIEURE  SERVICEMANETTE_BOUTON_A
//#define PROCESSUSBRAS_BOUTON_POSITION_INVERSEE SERVICEMANETTE_BOUTON_B

//#define PROCESSUSBRAS_VALEUR_POUR_INFERIEURE_VERS_SUPERIEURE 127
//#define PROCESSUSBRAS_VALEUR_POUR_INFERIEURE_VERS_VERTICALE 127
//#define PROCESSUSBRAS_VALEUR_POUR_SUPERIEURE_VERS_VERTICALE 127
//#define PROCESSUSBRAS_VALEUR_POUR_SUPERIEURE_VERS_INFERIEURE -128
//#define PROCESSUSBRAS_VALEUR_POUR_VERTICALE_VERS_SUPERIEURE -128
//#define PROCESSUSBRAS_VALEUR_POUR_VERTICALE_VERS_INFERIEURE -128
//#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_INFERIEURE_VERS_SUPERIEURE_EN_SECONDES 6
//#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_INFERIEURE_VERS_VERTICALE_EN_SECONDES 9
//#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_SUPERIEURE_VERS_VERTICALE_EN_SECONDES 3
//#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_SUPERIEURE_VERS_INFERIEURE_EN_SECONDES 6
//#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_VERTICALE_VERS_SUPERIEURE_EN_SECONDES 3
//#define PROCESSUSBRAS_TEMPS_MAXIMUM_POUR_VERTICALE_VERS_INFERIEURE_EN_SECONDES 9

//Dependances logicielles
//(copiez et adaptez ce qui suit dans "main.h")
//#define PROCESSUSBRAS_PHASE 0
//#define PROCESSUSBRAS_TEMPS_DE_DEPART_EN_SECONDES 2


//INFORMATION PUBLIQUE:
//Definitions publiques:
#define PROCESSUSBRAS_MODULE_EN_FONCTION     0
#define PROCESSUSBRAS_MODULE_PAS_EN_FONCTION 1
#define PROCESSUSBRAS_MODULE_EN_MODE_MANUEL  2
#define PROCESSUSBRAS_PAS_D_ERREUR           0
#define PROCESSUSBRAS_ERREUR_D_INTERRUPTEURS 1
#define PROCESSUSBRAS_ERREUR_DE_ROTATION     2

typedef struct
{
  unsigned char etatDuModule;  
  unsigned char statut;
} PROCESSUSBRAS;

//Fonctions publiques:
void processusBras_initialise(void);

//Variables publiques:
extern PROCESSUSBRAS processusBras;

#endif
